[package]
name = "valve-map"
version = "0.1.0"
edition = "2021"

[features]
default = ["meshing"]
meshing = ["dep:glam"]

[dependencies]
nom = "7.1"
anyhow = "1.0"
glam = { version = "0.21", optional = true }

[dev-dependencies]
macroquad = "0.3"
